# Generated by Django 3.2.5 on 2021-09-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='التقييم',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('المستوى', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='المتظوعين',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.CharField(max_length=45)),
                ('رقم_الهاتف', models.CharField(blank=True, max_length=45, null=True)),
                ('العنوان', models.CharField(blank=True, max_length=45, null=True)),
                ('التقييم', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.التقييم')),
            ],
        ),
        migrations.CreateModel(
            name='المفقودين',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.CharField(blank=True, max_length=45, null=True)),
                ('العمر', models.IntegerField()),
                ('الصلة', models.CharField(blank=True, max_length=45, null=True)),
                ('العنوان', models.CharField(blank=True, max_length=45, null=True)),
                ('رقم_هاتف_المبلغ', models.CharField(blank=True, max_length=45, null=True)),
                ('رقم_هاتف_المستلم', models.CharField(blank=True, max_length=45, null=True)),
                ('الحالة', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='النقاط',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_النقطة', models.CharField(max_length=45)),
                ('عدد_المتطوعين', models.IntegerField()),
                ('مكان_النقطة', models.CharField(blank=True, max_length=45, null=True)),
                ('مسؤول_النقطة', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.المتظوعين')),
            ],
        ),
        migrations.CreateModel(
            name='الموقف_اليومي',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('عدد_الاستمارات', models.IntegerField()),
                ('عدد_الباجات', models.IntegerField()),
                ('عدد_المفقودين', models.IntegerField()),
                ('عدد_المتطوعين', models.IntegerField()),
                ('التاريخ', models.DateField(auto_now_add=True)),
                ('النقطة', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.النقاط')),
            ],
        ),
    ]
